// resources/js/react/pages/Index.tsx
import { Button } from '@/components/ui/button';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from '@/components/ui/dialog';
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuItem,
    DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { PageHero } from '@/components/ui/saucebase';
import { useT } from '@/i18n';
import SiteLayout from '@/layouts/SiteLayout';
import { cn } from '@/lib/utils';
import { router, useForm } from '@inertiajs/react';
import { useEffect, useState } from 'react';

import type {
    RoadmapColumn,
    RoadmapItem,
    RoadmapTypeOption,
} from '../../types';
import ItemCard from '../components/ItemCard';
import { useVote } from '../hooks/useVote';

import IconArrowLeft from '~icons/heroicons/arrow-left';
import IconChevronDown from '~icons/heroicons/chevron-down';
import IconMap from '~icons/heroicons/map';
import IconPlus from '~icons/heroicons/plus';

const colorToVariant: Record<
    string,
    'default' | 'destructive' | 'secondary' | 'outline'
> = {
    primary: 'default',
    secondary: 'secondary',
    danger: 'destructive',
    warning: 'secondary',
    success: 'default',
    info: 'secondary',
    gray: 'outline',
};

const inputClass =
    'border-input bg-background placeholder:text-muted-foreground focus-visible:ring-ring flex w-full rounded-md border px-3 text-sm shadow-sm transition-colors focus-visible:ring-1 focus-visible:outline-none';

export default function Index({
    items,
    columns,
    types,
    sort,
    mine,
    authenticated,
    comments_enabled,
}: {
    items: RoadmapItem[];
    columns: RoadmapColumn[];
    types: RoadmapTypeOption[];
    sort: string;
    mine: boolean;
    authenticated: boolean;
    comments_enabled: boolean;
}) {
    const t = useT();

    const sortOptions = [
        { value: 'trending', label: t('Trending') },
        { value: 'new', label: t('Newest') },
        { value: 'old', label: t('Oldest') },
    ];

    const currentSortLabel =
        sortOptions.find((option) => option.value === sort)?.label ??
        sortOptions[0].label;

    /**
     * Sorting and filtering only redraw the backlog, which sits at the bottom of
     * the page, so the scroll position is kept.
     */
    function reload(query: { sort?: string; mine?: boolean }) {
        router.get(
            route('roadmap.index'),
            { sort, mine, ...query },
            { preserveState: true, preserveScroll: true, replace: true },
        );
    }

    // Voting updates the card before the server answers, so the list is local state.
    const [localItems, setLocalItems] = useState(items);

    useEffect(() => setLocalItems(items), [items]);

    const { vote, pending } = useVote(authenticated, ['items'], (id, change) =>
        setLocalItems((current) =>
            current.map((item) =>
                item.id === id ? { ...item, ...change } : item,
            ),
        ),
    );

    const board = columns.map((column) => ({
        ...column,
        items: localItems.filter((item) => item.status === column.value),
    }));

    const backlog = localItems.filter((item) => item.status === 'backlog');

    function typeVariant(item: RoadmapItem) {
        const type = types.find((option) => option.value === item.type);

        return colorToVariant[type?.color ?? 'primary'] ?? 'default';
    }

    function card(item: RoadmapItem, showStatus = false) {
        return (
            <ItemCard
                key={item.id}
                item={item}
                typeVariant={typeVariant(item)}
                commentsEnabled={comments_enabled}
                votePending={pending.has(item.id)}
                showStatus={showStatus}
                onVote={vote}
            />
        );
    }

    const [dialogOpen, setDialogOpen] = useState(false);

    const form = useForm({
        title: '',
        description: '',
        type: types[0]?.value ?? 'feature',
    });

    function openDialog() {
        if (!authenticated) {
            router.visit(route('login'));

            return;
        }

        form.reset();
        setDialogOpen(true);
    }

    function submitSuggestion(event: React.FormEvent) {
        event.preventDefault();

        form.post(route('roadmap.store'), {
            onSuccess: () => {
                setDialogOpen(false);
                form.reset();
            },
        });
    }

    return (
        <SiteLayout
            title={t('Roadmap')}
            description={t(
                'See what we are building and vote on what matters to you.',
            )}
            canonical={route('roadmap.index')}
        >
            <PageHero
                testId="roadmap-hero"
                title={t('Product Roadmap')}
                description={t(
                    'Everything we are working on, in the open. Upvote the ideas you want next, follow along as they move from planned to shipped, and send us anything that is missing.',
                )}
                icon={IconMap}
                actions={
                    <Button
                        data-testid="suggest-btn"
                        variant="secondary"
                        className="w-full sm:w-auto"
                        onClick={openDialog}
                    >
                        <IconPlus className="size-5" />
                        {t('Submit feedback')}
                    </Button>
                }
            />

            <div className="mx-auto w-full max-w-6xl px-8 py-16">
                {/* Sorting and filtering, at the top where they are easy to find */}
                {(localItems.length > 0 || mine) && (
                    <div className="mb-8 flex flex-wrap items-center gap-2">
                        {mine && (
                            <Button
                                data-testid="filter-mine-back"
                                variant="ghost"
                                className="gap-2"
                                onClick={() => reload({ mine: false })}
                            >
                                <IconArrowLeft className="size-4" />
                                {t('Back to the roadmap')}
                            </Button>
                        )}

                        <DropdownMenu>
                            <DropdownMenuTrigger asChild>
                                <Button
                                    variant="outline"
                                    data-testid="sort-trigger"
                                    className="gap-2"
                                >
                                    {t('Sort by')}: {currentSortLabel}
                                    <IconChevronDown className="size-4" />
                                </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="start">
                                {sortOptions.map((option) => (
                                    <DropdownMenuItem
                                        key={option.value}
                                        data-testid={`sort-${option.value}`}
                                        onSelect={() =>
                                            reload({ sort: option.value })
                                        }
                                    >
                                        {option.label}
                                    </DropdownMenuItem>
                                ))}
                            </DropdownMenuContent>
                        </DropdownMenu>

                        {authenticated && !mine && (
                            <Button
                                data-testid="filter-mine"
                                variant="outline"
                                className="ml-auto"
                                onClick={() => reload({ mine: true })}
                            >
                                {t('My feedback')}
                            </Button>
                        )}
                    </div>
                )}

                {localItems.length === 0 ? (
                    <div className="bg-muted/30 flex flex-col items-center justify-center gap-6 rounded-lg py-20 text-center">
                        <IconMap className="text-muted-foreground size-14" />
                        <p
                            className="text-muted-foreground"
                            data-testid="roadmap-empty"
                        >
                            {mine
                                ? t('You have not sent us any feedback yet.')
                                : t(
                                      'No roadmap items yet. Be the first to suggest a feature!',
                                  )}
                        </p>
                        <button
                            type="button"
                            data-testid="suggest-btn-empty"
                            className="border-secondary text-secondary hover:bg-secondary hover:text-secondary-foreground inline-flex items-center gap-2 rounded-md border px-4 py-1.5 text-sm transition-colors"
                            onClick={openDialog}
                        >
                            <IconPlus className="size-5" />
                            {t('Submit feedback')}
                        </button>
                    </div>
                ) : mine ? (
                    // Own submissions: a plain list, because one person's items can sit
                    // in statuses the board has no column for, review included.
                    <div
                        data-testid="roadmap-mine"
                        className="grid grid-cols-1 gap-3 lg:grid-cols-2"
                    >
                        {localItems.map((item) => card(item, true))}
                    </div>
                ) : (
                    <>
                        {/* One column per board status, stacked on small screens */}
                        <div
                            data-testid="roadmap-board"
                            className="grid grid-cols-1 gap-6 md:grid-cols-3"
                        >
                            {board.map((column) => (
                                <section
                                    key={column.value}
                                    data-testid={`roadmap-column-${column.value}`}
                                    className="flex flex-col gap-3"
                                >
                                    <h2 className="text-muted-foreground flex items-center gap-2 px-1 text-xs font-semibold tracking-wider uppercase">
                                        {column.label}
                                        <span className="font-normal">
                                            ({column.items.length})
                                        </span>
                                    </h2>

                                    {column.items.length === 0 && (
                                        <p className="text-muted-foreground bg-muted/30 rounded-lg px-3 py-6 text-center text-sm">
                                            {t('Nothing here yet.')}
                                        </p>
                                    )}

                                    {column.items.map((item) => card(item))}
                                </section>
                            ))}
                        </div>

                        {/* Accepted, but not scheduled yet */}
                        {backlog.length > 0 && (
                            <section
                                data-testid="roadmap-backlog"
                                className="mt-14"
                            >
                                <h2 className="mb-3 text-lg font-semibold">
                                    {t('Backlog')}{' '}
                                    <span className="text-muted-foreground font-normal">
                                        ({backlog.length})
                                    </span>
                                </h2>

                                <p className="text-muted-foreground mb-4 text-sm">
                                    {t(
                                        'Ideas we accepted but have not scheduled. Votes help us pick what comes next.',
                                    )}
                                </p>

                                <div className="grid grid-cols-1 gap-3 lg:grid-cols-2">
                                    {backlog.map((item) => card(item))}
                                </div>
                            </section>
                        )}
                    </>
                )}
            </div>

            <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
                <DialogContent className="sm:max-w-md">
                    <DialogHeader>
                        <DialogTitle>{t('Submit feedback')}</DialogTitle>
                        <DialogDescription>
                            {t(
                                'We review all submissions before publishing them to the roadmap.',
                            )}
                        </DialogDescription>
                    </DialogHeader>

                    <form onSubmit={submitSuggestion} className="space-y-4">
                        <div className="space-y-1.5">
                            <label className="text-sm font-medium">
                                {t('Type')}
                            </label>
                            <div className="flex gap-2">
                                {types.map((type) => (
                                    <button
                                        key={type.value}
                                        type="button"
                                        className={cn(
                                            'rounded-md border px-4 py-1.5 text-sm font-medium transition-colors',
                                            form.data.type === type.value
                                                ? 'bg-primary text-primary-foreground border-primary'
                                                : 'hover:bg-accent border-border',
                                        )}
                                        onClick={() =>
                                            form.setData('type', type.value)
                                        }
                                    >
                                        {type.label}
                                    </button>
                                ))}
                            </div>
                        </div>

                        <div className="space-y-1.5">
                            <label
                                htmlFor="suggest-title"
                                className="text-sm font-medium"
                            >
                                {t('Title')}{' '}
                                <span className="text-destructive">*</span>
                            </label>
                            <input
                                id="suggest-title"
                                data-testid="suggest-title"
                                value={form.data.title}
                                onChange={(event) =>
                                    form.setData('title', event.target.value)
                                }
                                type="text"
                                placeholder={t(
                                    'e.g. Dark mode, login bug, faster search…',
                                )}
                                maxLength={255}
                                className={cn(inputClass, 'h-9 py-1')}
                            />
                            {form.errors.title && (
                                <p className="text-destructive text-xs">
                                    {form.errors.title}
                                </p>
                            )}
                        </div>

                        <div className="space-y-1.5">
                            <label
                                htmlFor="suggest-description"
                                className="text-sm font-medium"
                            >
                                {t('Description')}
                            </label>
                            <textarea
                                id="suggest-description"
                                data-testid="suggest-description"
                                value={form.data.description}
                                onChange={(event) =>
                                    form.setData(
                                        'description',
                                        event.target.value,
                                    )
                                }
                                placeholder={t(
                                    "What's the problem or idea? Any details help.",
                                )}
                                rows={3}
                                maxLength={2000}
                                className={cn(inputClass, 'resize-none py-2')}
                            />
                            {form.errors.description && (
                                <p className="text-destructive text-xs">
                                    {form.errors.description}
                                </p>
                            )}
                        </div>

                        <DialogFooter>
                            <Button
                                data-testid="suggest-cancel-btn"
                                type="button"
                                variant="outline"
                                onClick={() => setDialogOpen(false)}
                            >
                                {t('Cancel')}
                            </Button>
                            <Button
                                data-testid="suggest-submit-btn"
                                type="submit"
                                disabled={form.processing}
                            >
                                {form.processing
                                    ? t('Submitting…')
                                    : t('Submit')}
                            </Button>
                        </DialogFooter>
                    </form>
                </DialogContent>
            </Dialog>
        </SiteLayout>
    );
}

// resources/js/pages/Index.vue
<script setup lang="ts">
import Badge from '@/components/ui/badge/Badge.vue';
import Button from '@/components/ui/button/Button.vue';
import {
    Dialog,
    DialogContent,
    DialogDescription,
    DialogFooter,
    DialogHeader,
    DialogTitle,
} from '@/components/ui/dialog';
import AppLayout from '@/layouts/AppLayout.vue';
import { router, useForm } from '@inertiajs/vue3';
import { trans } from 'laravel-vue-i18n';
import { computed, ref, watch } from 'vue';
import { toast } from 'vue-sonner';

import type { RoadmapItem } from '../types';

import IconAltArrowDownBold from '~icons/solar/alt-arrow-down-bold';
import IconAltArrowUpBold from '~icons/solar/alt-arrow-up-bold';
import IconMap from '~icons/heroicons/map';
import IconPlus from '~icons/heroicons/plus';

const props = defineProps<{
    items: RoadmapItem[];
    sort: string;
    types: Array<{ value: string; label: string; color: string }>;
}>();

const title = 'Roadmap';

// ── Static constants ─────────────────────────────────────────────────────────
const SORT_OPTIONS = [
    { value: 'top', label: 'Top' },
    { value: 'new', label: 'New' },
    { value: 'old', label: 'Old' },
];

const STATUS_CONFIG = [
    { value: 'in_progress', label: 'In Progress' },
    { value: 'approved', label: 'Planned' },
    { value: 'completed', label: 'Completed' },
] as const;

// ── Sorting ──────────────────────────────────────────────────────────────────
function changeSort(value: string) {
    router.get(route('roadmap.index'), { sort: value }, {
        preserveState: true,
        replace: true,
    });
}

// ── Optimistic local state ────────────────────────────────────────────────────
const localItems = ref(props.items.map(i => ({ ...i })));

watch(() => props.items, newItems => {
    localItems.value = newItems.map(i => ({ ...i }));
}, { deep: true });

// ── Status grouping ───────────────────────────────────────────────────────────
const groups = computed(() =>
    STATUS_CONFIG
        .map(({ value, label }) => ({
            status: value,
            label,
            items: localItems.value
                .filter(i => i.status === value)
                .sort((a, b) => props.sort === 'top' ? b.net_score - a.net_score : 0),
        }))
        .filter(g => g.items.length > 0),
);

// ── Vote class helpers ────────────────────────────────────────────────────────
function buttonClass(userVote: 'up' | 'down' | null, type: 'up' | 'down') {
    if (userVote !== type) return 'text-muted-foreground hover:bg-muted hover:text-foreground';
    return type === 'up' ? 'bg-secondary text-white' : 'bg-destructive text-destructive-foreground';
}

function scoreClass(vote: 'up' | 'down' | null) {
    if (vote === 'up') return 'bg-secondary text-white';
    if (vote === 'down') return 'bg-destructive text-destructive-foreground';
    return 'text-foreground';
}

// ── Voting ────────────────────────────────────────────────────────────────────
function showVoteToast(currentVote: 'up' | 'down' | null, type: 'up' | 'down') {
    if (currentVote === type) return toast.info(trans('Vote removed'));
    if (currentVote === null) return type === 'up' ? toast.success(trans('Upvoted!')) : toast.info(trans('Downvoted'));
    return type === 'up' ? toast.success(trans('Changed to upvote')) : toast.info(trans('Changed to downvote'));
}

function vote(item: RoadmapItem, type: 'up' | 'down') {
    const local = localItems.value.find(i => i.id === item.id);
    if (!local) return;

    const currentVote = local.user_vote;
    const originalScore = local.net_score;
    const delta = type === 'up' ? 1 : -1;

    // Optimistic update
    if (currentVote === type) {
        local.user_vote = null;
        local.net_score -= delta;
    } else {
        if (currentVote !== null) local.net_score -= currentVote === 'up' ? 1 : -1;
        local.net_score += delta;
        local.user_vote = type;
    }

    router.post(route('roadmap.vote', item.id), { type }, {
        preserveScroll: true,
        only: ['items'],
        onSuccess: () => showVoteToast(currentVote, type),
        onError: () => {
            local.net_score = originalScore;
            local.user_vote = currentVote;
        },
    });
}

// ── Suggestion dialog ─────────────────────────────────────────────────────────
const dialogOpen = ref(false);

const form = useForm({
    title: '',
    description: '',
    type: props.types[0]?.value ?? 'feature',
});

// ── Badge variant ─────────────────────────────────────────────────────────────
const colorToVariant: Record<string, 'default' | 'destructive' | 'secondary' | 'outline'> = {
    primary: 'default',
    secondary: 'secondary',
    danger: 'destructive',
    warning: 'secondary',
    success: 'default',
    info: 'secondary',
    gray: 'outline',
};

function typeBadgeVariant(item: RoadmapItem): 'default' | 'destructive' | 'secondary' | 'outline' {
    const found = props.types.find(t => t.value === item.type);
    return colorToVariant[found?.color ?? 'primary'] ?? 'default';
}

function openDialog() {
    form.reset();
    dialogOpen.value = true;
}

function submitSuggestion() {
    form.post(route('roadmap.store'), {
        onSuccess: () => {
            dialogOpen.value = false;
            form.reset();
        },
    });
}

// ── Formatting ────────────────────────────────────────────────────────────────
function formatDate(dateStr: string): string {
    return new Date(dateStr).toLocaleDateString(undefined, {
        month: 'short',
        day: 'numeric',
        year: 'numeric',
    });
}
</script>

<template>
    <AppLayout :title="title" :breadcrumbs="[{ title }]">
        <div class="flex flex-1 flex-col gap-6 p-6 pt-2">
            <div class="w-full max-w-3xl space-y-6">

                <!-- Header -->
                <div class="flex flex-col gap-4 mt-6 mb-10 sm:flex-row sm:items-center sm:justify-between">
                    <div class="flex items-center gap-3">
                        <div class="bg-primary/10 text-primary rounded-full p-4">
                            <IconMap class="size-10" />
                        </div>
                        <div>
                            <h1 class="text-2xl font-bold tracking-tight">{{ $t('Product Roadmap') }}</h1>
                            <p class="text-muted-foreground text-sm">
                                {{ $t('Vote on features and suggest new ideas.') }}
                            </p>
                        </div>
                    </div>

                    <Button data-testid="suggest-btn" class="w-full sm:w-auto" @click="openDialog">
                        <IconPlus class="size-5 text-white" />
                        {{ $t('Submit feedback') }}
                    </Button>
                </div>

                <!-- Sort controls -->
                <div v-if="localItems.length > 0" class="flex items-center gap-1.5">
                    <span class="text-muted-foreground text-xs mr-1">{{ $t('Sort:') }}</span>
                    <button
                        v-for="opt in SORT_OPTIONS"
                        :key="opt.value"
                        type="button"
                        :class="[
                            'rounded-md border px-3 py-1 text-xs font-medium transition-colors',
                            sort === opt.value
                                ? 'bg-primary text-primary-foreground border-primary'
                                : 'hover:bg-accent border-border text-muted-foreground',
                        ]"
                        @click="changeSort(opt.value)"
                    >
                        {{ $t(opt.label) }}
                    </button>
                </div>

                <!-- Empty state -->
                <div
                    v-if="localItems.length === 0"
                    class="flex flex-col items-center justify-center py-20 gap-6 text-center bg-muted/30 rounded-lg"
                >
                    <IconMap class="text-muted-foreground size-14 " />
                    <p class="text-muted-foreground">
                        {{ $t('No roadmap items yet. Be the first to suggest a feature!') }}
                    </p>
                    <button type="button" data-testid="suggest-btn-empty" class="rounded-md border border-primary px-4 py-1.5 text-sm text-primary hover:bg-primary hover:text-primary-foreground transition-colors" @click="openDialog">
                        {{ $t('Submit feedback') }}
                    </button>
                </div>

                <!-- Grouped item list -->
                <div v-for="group in groups" :key="group.status" class="space-y-2">
                    <!-- Group header -->
                    <p class="text-muted-foreground text-xs font-semibold uppercase tracking-wider px-1">
                        {{ $t(group.label) }}
                        <span class="ml-1 font-normal">({{ group.items.length }})</span>
                    </p>

                    <!-- Items -->
                    <TransitionGroup tag="div" class="flex flex-col gap-2" move-class="transition-transform duration-500 ease-out">
                        <div
                            v-for="item in group.items"
                            :key="item.id"
                            class="relative flex items-stretch gap-0 rounded border overflow-hidden transition-colors bg-muted/50 hover:bg-muted/80 dark:bg-muted/20 dark:hover:bg-muted/40"
                        >
                            <!-- Vote box -->
                            <div
                                :data-testid="`vote-box-${item.id}`"
                                :data-user-vote="item.user_vote ?? 'none'"
                                class="flex w-12 shrink-0 flex-col border-r"
                            >
                                <button
                                    :data-testid="`upvote-btn-${item.id}`"
                                    :class="['flex cursor-pointer items-center justify-center py-3 transition-colors', buttonClass(item.user_vote, 'up')]"
                                    @click="vote(item, 'up')"
                                >
                                    <IconAltArrowUpBold class="size-5" />
                                </button>
                                <span
                                    :data-testid="`vote-score-${item.id}`"
                                    :class="['flex items-center justify-center py-2 text-sm font-semibold tabular-nums', scoreClass(item.user_vote)]"
                                >
                                    {{ item.net_score }}
                                </span>
                                <button
                                    :data-testid="`downvote-btn-${item.id}`"
                                    :class="['flex cursor-pointer items-center justify-center py-3 transition-colors', buttonClass(item.user_vote, 'down')]"
                                    @click="vote(item, 'down')"
                                >
                                    <IconAltArrowDownBold class="size-5" />
                                </button>
                            </div>

                            <!-- Content -->
                            <div class="flex flex-1 flex-col justify-center gap-1 px-4 py-3">
                                <p class="font-semibold leading-snug">
                                    {{ item.title }}
                                </p>
                                <Badge
                                    :variant="typeBadgeVariant(item)"
                                    class="absolute top-0 right-0 rounded-none rounded-bl text-xs text-white"
                                >
                                    {{ item.type_label }}
                                </Badge>
                                <p
                                    v-if="item.description"
                                    class="line-clamp-1 text-sm"
                                >
                                    {{ item.description }}
                                </p>
                                <p class="text-muted-foreground text-xs mt-2">
                                    {{ $t('Created on') }} {{ formatDate(item.created_at) }}
                                </p>
                            </div>
                        </div>
                    </TransitionGroup>
                </div>

            </div>
        </div>

        <!-- Suggestion dialog -->
        <Dialog v-model:open="dialogOpen">
            <DialogContent class="sm:max-w-md">
                <DialogHeader>
                    <DialogTitle>{{ $t('Submit feedback') }}</DialogTitle>
                    <DialogDescription>
                        {{ $t('We review all submissions before publishing them to the roadmap.') }}
                    </DialogDescription>
                </DialogHeader>

                <form @submit.prevent="submitSuggestion" class="space-y-4">
                    <!-- Type toggle -->
                    <div class="space-y-1.5">
                        <label class="text-sm font-medium">{{ $t('Type') }}</label>
                        <div class="flex gap-2">
                            <button
                                v-for="t in types"
                                :key="t.value"
                                type="button"
                                :class="[
                                    'rounded-md border px-4 py-1.5 text-sm font-medium transition-colors',
                                    form.type === t.value
                                        ? 'bg-primary text-primary-foreground border-primary'
                                        : 'hover:bg-accent border-border',
                                ]"
                                @click="form.type = t.value"
                            >
                                {{ t.label }}
                            </button>
                        </div>
                    </div>

                    <!-- Title -->
                    <div class="space-y-1.5">
                        <label for="suggest-title" class="text-sm font-medium">
                            {{ $t('Title') }} <span class="text-destructive">*</span>
                        </label>
                        <input
                            id="suggest-title"
                            data-testid="suggest-title"
                            v-model="form.title"
                            type="text"
                            :placeholder="$t('e.g. Dark mode, login bug, faster search…')"
                            maxlength="255"
                            class="border-input bg-background placeholder:text-muted-foreground focus-visible:ring-ring flex h-9 w-full rounded-md border px-3 py-1 text-sm shadow-sm transition-colors focus-visible:ring-1 focus-visible:outline-none"
                        />
                        <p v-if="form.errors.title" class="text-destructive text-xs">{{ form.errors.title }}</p>
                    </div>

                    <!-- Description -->
                    <div class="space-y-1.5">
                        <label for="suggest-description" class="text-sm font-medium">
                            {{ $t('Description') }}
                        </label>
                        <textarea
                            id="suggest-description"
                            data-testid="suggest-description"
                            v-model="form.description"
                            :placeholder="$t('What\'s the problem or idea? Any details help.')"
                            rows="3"
                            maxlength="2000"
                            class="border-input bg-background placeholder:text-muted-foreground focus-visible:ring-ring flex w-full rounded-md border px-3 py-2 text-sm shadow-sm transition-colors focus-visible:ring-1 focus-visible:outline-none resize-none"
                        />
                        <p v-if="form.errors.description" class="text-destructive text-xs">{{ form.errors.description }}</p>
                    </div>

                    <DialogFooter>
                        <Button data-testid="suggest-cancel-btn" type="button" variant="outline" @click="dialogOpen = false">
                            {{ $t('Cancel') }}
                        </Button>
                        <Button data-testid="suggest-submit-btn" type="submit" :disabled="form.processing">
                            {{ form.processing ? $t('Submitting…') : $t('Submit') }}
                        </Button>
                    </DialogFooter>
                </form>
            </DialogContent>
        </Dialog>
    </AppLayout>
</template>
